#! /bin/sh

# System #

## Autostart
pkill -x sxhkd; sxhkd &
feh --bg-fill "$HOME/nixos/backgrounds/def.png" &
"$HOME/nixos/modules/dotfiles/polybar/scripts/launch.sh" &
dunst &
picom --config "$HOME/nixos/dotfiles/picom/picom.conf" &

## Workspaces
bspc monitor -d 1 2 3 4 5

# Looks #

## Border
bspc config border_width 3

bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#4C566A"
bspc config active_border_color "#4C566A"
bspc config presel_feedback_color "#BF616A"

## Gaps
bspc config window_gap 8 

bspc config left_padding 10
bspc config right_padding 10
bspc config bottom_padding 10
bspc config top_padding 50

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
