[module/bspwm]
type = internal/bspwm

; Show only workspaces from this monitor
pin-workspaces = true

; Allow clicking & scrolling w/ mouse or trackpad
enable-click = true
enable-scroll = true
wrapping-scroll = true

; Display the workspaces as symbols
format = <label-state>

; Urgent workspace
label-urgent = "◉"
label-urgent-foreground = ${colors.red}
; JetBrainsMono Nerd Font 2
label-urgent-font = 4 
label-urgent-padding = 2

; Focused workspace
label-focused = "●" 
label-focused-foreground = ${colors.cyan}
; JetBrainsMono Nerd Font 2
label-focused-font = 4
label-focused-padding = 2

; Unfocused workspace containing windows
label-occupied = "◉"
label-occupied-foreground = ${colors.yellow}
; JetBrainsMono Nerd Font 2
label-occupied-font = 4
label-occupied-padding = 2

; Unfocused empty workspace
label-empty = "○"
label-empty-foreground = ${colors.primary}
; JetBrainsMono Nerd Font 2
label-empty-font = 4
label-empty-padding = 2

; Workspace visible on another monitor
label-visible = "◉"
label-visible-foreground = ${colors.green}
; JetBrainsMono Nerd Font 2
label-visible-font = 4
label-visible-padding = 2

; No separator between the workspaces
label-separator = ""
