[module/network]
type = custom/script 
interval = 5

# Launching the script to tell the signal-strength
exec = "$HOME/nixos/modules/dotfiles/polybar/scripts/network.sh"

format = <label>
; JetBrainsMono Nerd Font 1
format-font = 3
label = %output%
