[bar/bar]
# Bar
width = 80%
height = 25pt
radius = 7 

top = true
offset-x = 10%
offset-y = 7

override-redirect = true
wm-restack = i3

background = ${colors.background}
foreground = ${colors.foreground}

# Modules
padding-left = 2
padding-right = 4

module-margin = 3

separator = "" 
separator-foreground = ${colors.disabled}

tray-position = none

# IBM Plex Sans
font-0 = IBM Plex Sans:size=12;2

# Font Awesome
font-1 = FontAwesome:size=10;1

# JetBrainsMono Nerd Font
font-2 = JetBrainsMono Nerd Font:size=12;2
font-3 = JetBrainsMono Nerd Font:size=17;2

fixed-center = true
modules-left = bspwm 
modules-center = date
modules-right = network battery 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
